name: Add issue to project
on:
  pull_request:
    types:
      - opened
      
jobs:
  track_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get project data
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_CI_ISSUES }}
          ORGANIZATION: DUNE-DAQ
          PROJECT_NUMBER: 5
        run: |
          gh api graphql -f query='
            query($org: String!, $number: Int!) {
              organization(login: $org){
                projectNext(number: $number) {
                  id
                  fields(first:20) {
                    nodes {
                      id
                      name
                      settings
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER > project_data.json

          echo 'PROJECT_ID='$(jq '.data.organization.projectNext.id' project_data.json) >> $GITHUB_ENV
                    
      - name: Add issue to project
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_CI_ISSUES }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
            echo github.event.number = ${{ github.event.number  }}
            echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
            echo github.event.issue.number = ${{ github.event.issue.number }}

            item_id="$( gh api graphql -f query='
            mutation($project:ID!, $issue:ID!) {
              addProjectNextItem(input: {projectId: $project, contentId: $issue}) {
                projectNextItem {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f issue=$PR_NUMBER --jq '.data.addProjectNextItem.projectNextItem.id')"        
